using System.Collections.ObjectModel;
using System.Text.Json;

namespace peeku;

public static class ToolRegistry
{
  public static IReadOnlyList<ToolDescriptor> All => _all;

  private static readonly ReadOnlyCollection<ToolDescriptor> _all = new(BuildAll());
  private static readonly Dictionary<string, ToolDescriptor> _byName = _all.ToDictionary(x => x.Name, StringComparer.Ordinal);

  public static bool TryGet(string name, out ToolDescriptor tool)
    => _byName.TryGetValue(name, out tool!);

  public static ToolDescriptor Get(string name)
    => _byName.TryGetValue(name, out var tool)
      ? tool
      : throw new KeyNotFoundException($"Unknown tool: '{name}'.");

  private static List<ToolDescriptor> BuildAll()
  {
    return
    [
      Create("peeku_doctor", "Doctor", "Self-checks (optionally deep: capture + UIA).", DoctorInputSchemaJson, DoctorOutputSchemaJson),
      Create("peeku_windows_list", "Windows List", "List windows with optional filters.", WindowsListInputSchemaJson, WindowsListOutputSchemaJson),
      Create("peeku_windows_focused", "Windows Focused", "Get focused window.", WindowsFocusedInputSchemaJson, WindowsFocusedOutputSchemaJson),
      Create("peeku_windows_focus", "Windows Focus", "Bring a window to the foreground.", WindowsFocusInputSchemaJson, WindowsFocusedOutputSchemaJson),
      Create("peeku_capture_image", "Capture Image", "Capture a screenshot/image of a target.", CaptureImageInputSchemaJson, CaptureImageOutputSchemaJson),
      Create("peeku_uia_snapshot", "UIA Snapshot", "Capture a UI Automation snapshot for a target.", UiaSnapshotInputSchemaJson, UiaSnapshotOutputSchemaJson),
      Create("peeku_see", "See", "Capture image + UIA snapshot.", SeeInputSchemaJson, SeeOutputSchemaJson),
      Create("peeku_find", "Find", "Find elements by selector.", FindInputSchemaJson, FindOutputSchemaJson),
      Create("peeku_element_get", "Element Get", "Get element details/properties.", ElementGetInputSchemaJson, ElementGetOutputSchemaJson),
      Create("peeku_click", "Click", "Click an element.", ClickInputSchemaJson, ClickOutputSchemaJson),
      Create("peeku_invoke", "Invoke", "Invoke an element.", InvokeInputSchemaJson, ClickOutputSchemaJson),
      Create("peeku_set_value", "Set Value", "Set element value.", SetValueInputSchemaJson, SetValueOutputSchemaJson),
      Create("peeku_type", "Type", "Type text into an element.", TypeInputSchemaJson, TypeOutputSchemaJson),
      Create("peeku_scroll", "Scroll", "Scroll on an element/target.", ScrollInputSchemaJson, MinimalActionOutputSchemaJson),
      Create("peeku_hotkey", "Hotkey", "Send a hotkey chord.", HotkeyInputSchemaJson, MinimalActionOutputSchemaJson),
      Create("peeku_press", "Press", "Press one or more named keys in sequence.", PressInputSchemaJson, MinimalActionOutputSchemaJson),
      Create("peeku_observe", "Observe", "Observe UIA events (bounded).", ObserveInputSchemaJson, ObserveOutputSchemaJson),
      Create("peeku_wait", "Wait", "Wait until selector matches.", WaitInputSchemaJson, WaitOutputSchemaJson),
      Create("peeku_batch", "Batch", "Execute a batch of tool calls.", BatchInputSchemaJson, BatchOutputSchemaJson),
      Create("peeku_diff", "Diff", "Snapshot two targets and diff their UIA trees by refId.", DiffInputSchemaJson, DiffOutputSchemaJson),
      Create("peeku_element_from_point", "Element From Point", "Resolve element at screen pixel (hit-test by coordinate).", ElementFromPointInputSchemaJson, ElementFromPointOutputSchemaJson),
      Create("peeku_window_move", "Window Move", "Move a window to the given screen coordinates.", WindowMoveInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_resize", "Window Resize", "Resize a window to the given dimensions.", WindowResizeInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_set_bounds", "Window Set Bounds", "Move and resize a window in one call.", WindowSetBoundsInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_minimize", "Window Minimize", "Minimize a window.", WindowStateInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_maximize", "Window Maximize", "Maximize a window.", WindowStateInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_restore", "Window Restore", "Restore a minimized or maximized window.", WindowStateInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_window_close", "Window Close", "Close a window gracefully (WM_CLOSE) and report whether it closed.", WindowCloseInputSchemaJson, WindowActionOutputSchemaJson),
      Create("peeku_app_launch", "App Launch", "Launch an application by path or AUMID.", AppLaunchInputSchemaJson, AppLaunchOutputSchemaJson),
      Create("peeku_app_quit", "App Quit", "Quit an application gracefully (WM_CLOSE loop) then force-kill on timeout.", AppQuitInputSchemaJson, AppQuitOutputSchemaJson),
      Create("peeku_app_relaunch", "App Relaunch", "Relaunch a running application by pid or process name (captures exe path, quits, re-launches).", AppRelaunchInputSchemaJson, AppRelaunchOutputSchemaJson),
      Create("peeku_app_list", "App List", "List distinct applications that own at least one visible top-level window.", AppListInputSchemaJson, AppListOutputSchemaJson),
    ];
  }

  private static ToolDescriptor Create(
    string name,
    string title,
    string description,
    string inputSchemaJson,
    string outputSchemaJson)
  {
    var inputSchema = ParseSchema(name, "inputSchema", inputSchemaJson);
    var outputSchema = ParseSchema(name, "outputSchema", outputSchemaJson);
    return new(
      name,
      title,
      description,
      inputSchema,
      outputSchema,
      static (_, _) => Task.FromException<object>(new NotImplementedException("Tool handler not implemented.")));
  }

  private static JsonDocument ParseSchema(string toolName, string schemaName, string json)
  {
    try
    {
      return JsonDocument.Parse(json);
    }
    catch (Exception ex)
    {
      throw new InvalidOperationException($"Invalid {schemaName} for tool '{toolName}'.", ex);
    }
  }

  private const string DoctorInputSchemaJson = """{"type":"object","properties":{"deep":{"type":"boolean","default":false,"description":"Run slower checks (capture + UIA)"}}}""";
  private const string DoctorOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"checks":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string"},"ok":{"type":"boolean"},"details":{"type":"string"}},"required":["name","ok"]}}},"required":["ok","traceId","checks"]}""";

  private const string WindowsListInputSchemaJson = """{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"limit":{"type":"integer","default":50}}}""";
  private const string WindowsListOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"windows":{"type":"array","items":{"type":"object","properties":{"hwndHex":{"type":"string"},"title":{"type":"string"},"processId":{"type":"integer"},"processName":{"type":"string"}},"required":["hwndHex","processId"]}}},"required":["ok","traceId","windows"]}""";

  private const string WindowsFocusedInputSchemaJson = """{"type":"object","properties":{}}""";
  private const string WindowsFocusedOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"window":{"type":"object","properties":{"hwndHex":{"type":"string"},"title":{"type":"string"},"processId":{"type":"integer"},"processName":{"type":"string"}},"required":["hwndHex","processId"]}},"required":["ok","traceId","window"]}""";

  private const string CaptureImageInputSchemaJson = """{"type":"object","properties":{"target":{"description":"What to capture","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer","description":"Required when kind=screen"},"hwndHex":{"type":"string","description":"Required when kind=window_hwnd; e.g. 0x0003059A"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"out":{"type":"string","description":"Optional output path on disk"},"includeBase64":{"type":"boolean","default":false}},"required":["target"]}""";
  private const string CaptureImageOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"imagePath":{"type":"string"},"mimeType":{"type":"string","default":"image/png"},"base64":{"type":"string","description":"Present only if includeBase64=true"},"width":{"type":"integer"},"height":{"type":"integer"}},"required":["ok","traceId","imagePath","mimeType","width","height"]}""";

  private const string UiaSnapshotInputSchemaJson = """{"type":"object","properties":{"target":{"description":"Window/screen/desktop to snapshot","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"depth":{"type":"integer","default":6},"maxNodes":{"type":"integer","default":5000},"includeProperties":{"type":"string","enum":["basic","all"],"default":"basic"}},"required":["target"]}""";
  private const string UiaSnapshotOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"snapshotId":{"type":"string"},"root":{"type":"object"},"elements":{"type":"array","items":{"type":"object","properties":{"element":{"type":"object"},"rect":{"type":"object"},"name":{"type":"string"},"controlType":{"type":"string"},"automationId":{"type":"string"},"className":{"type":"string"},"actions":{"type":"array","items":{"type":"string"}},"state":{"type":"object"}}}}},"required":["ok","traceId","snapshotId","root","elements"]}""";

  private const string SeeInputSchemaJson = """{"type":"object","properties":{"target":{"description":"Window/screen/desktop to capture and snapshot","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"depth":{"type":"integer","default":6},"maxNodes":{"type":"integer","default":5000},"includeProperties":{"type":"string","enum":["basic","all"],"default":"basic"},"includeBase64":{"type":"boolean","default":false}},"required":["target"]}""";
  private const string SeeOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"image":{"type":"object"},"snapshotId":{"type":"string"},"elements":{"type":"array","items":{"type":"object","properties":{"element":{"type":"object"},"rect":{"type":"object"},"name":{"type":"string"},"controlType":{"type":"string"},"automationId":{"type":"string"},"className":{"type":"string"},"actions":{"type":"array","items":{"type":"string"}},"state":{"type":"object"}}}}},"required":["ok","traceId","image","snapshotId","elements"]}""";

  private const string FindInputSchemaJson = """{"type":"object","properties":{"selector":{"description":"Element selector; string shorthand or object with expr","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string","description":"Path selector expression"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"description":"Optional; defaults to focused window","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"limit":{"type":"integer","default":20}},"required":["selector"]}""";
  private const string FindOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"matches":{"type":"array","items":{"type":"object","properties":{"element":{"type":"object"},"name":{"type":"string"},"automationId":{"type":"string"},"controlType":{"type":"string"},"rect":{"type":"object"},"score":{"type":"number"}},"required":["element","rect","score"]}}},"required":["ok","traceId","matches"]}""";

  private const string ElementGetInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"includeProperties":{"type":"string","enum":["basic","all"],"default":"all"}}}""";
  private const string ElementGetOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"element":{"type":"object","properties":{"element":{"type":"object"},"rect":{"type":"object"},"name":{"type":"string"},"controlType":{"type":"string"},"automationId":{"type":"string"},"className":{"type":"string"},"actions":{"type":"array","items":{"type":"string"}},"state":{"type":"object"}}},"properties":{"type":"object"},"patterns":{"type":"array","items":{"type":"string"}},"rect":{"type":"object"}},"required":["ok","traceId","element","properties","patterns","rect"]}""";

  private const string ClickInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"method":{"type":"string","enum":["auto","uia","input"],"default":"auto"},"foreground":{"type":"boolean","default":false,"description":"Use SendInput synthetic click (steals + restores foreground). Implied by method=input."},"x":{"type":"integer","description":"Window-relative X coordinate (physical pixels). Provide with y to skip element resolution."},"y":{"type":"integer","description":"Window-relative Y coordinate (physical pixels). Provide with x to skip element resolution."},"globalCoords":{"type":"boolean","default":false,"description":"Treat x/y as screen-absolute physical pixels (skip window offset)."},"double":{"type":"boolean","default":false,"description":"Double-click: two down/up pairs in one SendInput batch."},"right":{"type":"boolean","default":false,"description":"Right-button click instead of left."}}}""";
  private const string ClickOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"methodUsed":{"type":"string"},"clickedElement":{"type":"object"}},"required":["ok","traceId","methodUsed"]}""";

  private const string InvokeInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]}}}""";

  private const string SetValueInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"value":{"type":"string"}},"required":["value"]}""";
  private const string SetValueOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"methodUsed":{"type":"string"},"evidence":{"type":"object"}},"required":["ok","traceId"]}""";

  private const string TypeInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"method":{"type":"string","enum":["auto","uia","input"],"default":"auto"},"foreground":{"type":"boolean","default":false,"description":"Use SendInput synthetic UNICODE keystrokes (steals + restores foreground). Works on password/UIA-blocked fields. Implied by method=input."},"text":{"type":"string"},"append":{"type":"boolean","default":true},"delayMs":{"type":"integer","default":0}},"required":["text"]}""";
  private const string TypeOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"methodUsed":{"type":"string"},"evidence":{"type":"object"}},"required":["ok","traceId"]}""";
  private const string MinimalActionOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"}},"required":["ok","traceId"]}""";

  private const string ScrollInputSchemaJson = """{"type":"object","properties":{"elementRef":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}},"required":["refId"]}]},"selector":{"description":"Exactly one of elementRef or selector required","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"direction":{"type":"string","enum":["vertical","horizontal"],"default":"vertical"},"delta":{"type":"integer","description":"Wheel delta in notches, e.g. 120/-120; provide one of delta or lines"},"lines":{"type":"integer","description":"Number of lines to scroll; provide one of delta or lines"}},"required":[]}""";

  private const string HotkeyInputSchemaJson = """{"type":"object","properties":{"keys":{"type":"string","description":"e.g. CTRL+SHIFT+S"}},"required":["keys"]}""";

  private const string WindowsFocusInputSchemaJson = """{"type":"object","properties":{"target":{"description":"Window to bring to the foreground","oneOf":[{"type":"string","enum":["focused_window","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["focused_window","window_hwnd","window_query"]},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]}},"required":["target"]}""";

  private const string PressInputSchemaJson = """{"type":"object","properties":{"keys":{"type":"array","items":{"type":"string"},"description":"Named keys to press in sequence, e.g. [\"enter\"], [\"tab\",\"tab\"], [\"down\"]. Distinct from hotkey chords."},"count":{"type":"integer","default":1,"description":"Repeat the whole key sequence this many times"},"delayMs":{"type":"integer","description":"Delay between keys (ms)"},"holdMs":{"type":"integer","description":"Hold each key down this long before release (ms)"},"target":{"description":"Optional window to focus before sending keys (else current foreground)","oneOf":[{"type":"string","enum":["focused_window","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["focused_window","window_hwnd","window_query"]},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]}},"required":["keys"]}""";

  private const string ObserveInputSchemaJson = """{"type":"object","properties":{"target":{"description":"Window/screen/desktop to observe","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"events":{"type":"array","items":{"type":"string","enum":["structure","property","focus"]},"default":["structure","property","focus"]},"durationMs":{"type":"integer","default":10000},"maxEvents":{"type":"integer","default":200}},"required":["target"]}""";
  private const string ObserveOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"events":{"type":"array","items":{"type":"object","properties":{"timestamp":{"type":"string"},"eventType":{"type":"string"},"element":{"type":"object"},"changeType":{"type":"string"},"changedProperty":{"type":"string"},"oldValue":{},"newValue":{},"hwnd":{"type":"string"},"source":{"type":"string"}},"required":["timestamp","eventType"]}}},"required":["ok","traceId","events"]}""";

  private const string WaitInputSchemaJson = """{"type":"object","properties":{"selector":{"description":"Selector to wait for","oneOf":[{"type":"string"},{"type":"object","properties":{"expr":{"type":"string"},"preferCachedSnapshot":{"type":"boolean","default":true}},"required":["expr"]}]},"target":{"description":"Window/screen/desktop to observe","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"timeoutMs":{"type":"integer","default":10000},"condition":{"type":"string","enum":["exists","notExists","enabled","disabled","visible","hidden","focused","toggleOn","toggleOff","expanded","collapsed","selected","notSelected","valueEquals","valueContains","nameEquals","nameContains"],"default":"exists","description":"Condition to evaluate; exists/notExists use snapshot path, all others use live path"},"value":{"type":"string","description":"Expected value for valueEquals/valueContains/nameEquals/nameContains conditions"}},"required":["selector","target"]}""";
  private const string WaitOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"found":{"type":"boolean"},"element":{"type":"object","properties":{"refId":{"type":"string"},"snapshotId":{"type":"string"}}}},"required":["ok","traceId","found"]}""";

  private const string BatchInputSchemaJson = """{"type":"object","properties":{"ops":{"type":"array","items":{"type":"object","properties":{"tool":{"type":"string"},"args":{"type":"object"}},"required":["tool","args"]}},"stopOnError":{"type":"boolean","default":true}},"required":["ops"]}""";
  private const string BatchOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"results":{"type":"array","items":{"type":"object","properties":{"tool":{"type":"string"},"ok":{"type":"boolean"},"durationMs":{"type":"integer"},"result":{},"error":{"type":"object"}},"required":["tool","ok","durationMs"]}}},"required":["ok","traceId","results"]}""";

  private const string DiffInputSchemaJson = """{"type":"object","properties":{"targetBefore":{"description":"Before snapshot target","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"targetAfter":{"description":"After snapshot target","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"depth":{"type":"integer","default":6},"maxNodes":{"type":"integer","default":5000},"includeProperties":{"type":"string","enum":["basic","all"],"default":"basic"}},"required":["targetBefore","targetAfter"]}""";
  private const string DiffOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"snapshotIdBefore":{"type":"string"},"snapshotIdAfter":{"type":"string"},"delta":{"type":"object","properties":{"added":{"type":"array","items":{"type":"object"}},"removed":{"type":"array","items":{"type":"object"}},"truncated":{"type":"boolean"}}}},"required":["ok","traceId"]}""";
  private const string ElementFromPointInputSchemaJson = """{"type":"object","properties":{"x":{"type":"integer","description":"Physical screen X coordinate"},"y":{"type":"integer","description":"Physical screen Y coordinate"},"target":{"description":"Optional target (unused for hit-test, reserved)","oneOf":[{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["desktop","focused_window","screen","window_hwnd","window_query"]},"screenIndex":{"type":"integer"},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]},"includeProperties":{"type":"string","enum":["basic","all"],"default":"all"}},"required":["x","y"]}""";
  private const string ElementFromPointOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"element":{"type":"object"},"ancestors":{"type":"array","items":{"type":"object"}}},"required":["ok","traceId","element","ancestors"]}""";

  // ── Window management (S3) ────────────────────────────────────────────────
  private const string WindowTargetSchema = """{"oneOf":[{"type":"string","enum":["focused_window","window_hwnd","window_query"]},{"type":"object","properties":{"kind":{"type":"string","enum":["focused_window","window_hwnd","window_query"]},"hwndHex":{"type":"string"},"query":{"type":"object","properties":{"titleContains":{"type":"string"},"processName":{"type":"string"},"processId":{"type":"integer"}}}},"required":["kind"]}]}""";
  private const string WindowMoveInputSchemaJson = """{"type":"object","properties":{"target":""" + WindowTargetSchema + ""","x":{"type":"integer","description":"Screen X (physical pixels)"},"y":{"type":"integer","description":"Screen Y (physical pixels)"}},"required":["target","x","y"]}""";
  private const string WindowResizeInputSchemaJson = """{"type":"object","properties":{"target":""" + WindowTargetSchema + ""","width":{"type":"integer","description":"Width (physical pixels)"},"height":{"type":"integer","description":"Height (physical pixels)"}},"required":["target","width","height"]}""";
  private const string WindowSetBoundsInputSchemaJson = """{"type":"object","properties":{"target":""" + WindowTargetSchema + ""","x":{"type":"integer"},"y":{"type":"integer"},"width":{"type":"integer"},"height":{"type":"integer"}},"required":["target","x","y","width","height"]}""";
  private const string WindowStateInputSchemaJson = """{"type":"object","properties":{"target":""" + WindowTargetSchema + """},"required":["target"]}""";
  private const string WindowCloseInputSchemaJson = """{"type":"object","properties":{"target":""" + WindowTargetSchema + ""","waitMs":{"type":"integer","default":2000,"description":"Max ms to wait for window to close; poll IsWindow until gone or elapsed."}},"required":["target"]}""";
  private const string WindowActionOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"evidence":{"type":"object","description":"For close: {closed:bool}; others empty."}},"required":["ok","traceId"]}""";

  // ── App lifecycle (S4) ────────────────────────────────────────────────────
  private const string AppLaunchInputSchemaJson = """{"type":"object","properties":{"target":{"type":"string","description":"File path, URI, or AUMID (e.g. Microsoft.WindowsCalculator_8wekyb3d8bbwe!App)"},"args":{"type":"string","description":"Optional command-line arguments"},"waitUntilReady":{"type":"boolean","default":false,"description":"Wait for input-idle and a top-level window before returning"},"waitMs":{"type":"integer","default":5000,"description":"Max ms to wait when waitUntilReady=true"},"noFocus":{"type":"boolean","default":false,"description":"Skip post-launch BringToForeground activation"}},"required":["target"]}""";
  private const string AppLaunchOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"processId":{"type":"integer"},"window":{"type":"object","description":"First top-level window of the launched process, if found"}},"required":["ok","traceId"]}""";

  private const string AppQuitInputSchemaJson = """{"type":"object","properties":{"processId":{"type":"integer","description":"PID to quit"},"processName":{"type":"string","description":"Process name to quit (used when processId is absent)"},"force":{"type":"boolean","default":false,"description":"Kill immediately without WM_CLOSE grace period"},"all":{"type":"boolean","default":false,"description":"Quit all processes matching processName"},"except":{"type":"array","items":{"type":"string"},"description":"Process names to skip when using --all"},"waitMs":{"type":"integer","default":3000,"description":"Grace period before force-kill (ms)"}},"required":[]}""";
  private const string AppQuitOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"closed":{"type":"integer","description":"Processes closed gracefully"},"killed":{"type":"integer","description":"Processes force-killed"}},"required":["ok","traceId"]}""";

  private const string AppRelaunchInputSchemaJson = """{"type":"object","properties":{"processId":{"type":"integer","description":"PID of the running process to relaunch"},"processName":{"type":"string","description":"Process name to relaunch (used when processId is absent)"},"waitUntilReady":{"type":"boolean","default":false,"description":"Wait for input-idle and a top-level window before returning"},"waitMs":{"type":"integer","default":5000,"description":"Max ms for both graceful-quit grace and launch readiness"},"noFocus":{"type":"boolean","default":false,"description":"Skip post-launch BringToForeground activation"}},"required":[]}""";
  private const string AppRelaunchOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"processId":{"type":"integer","description":"PID of the relaunched process"},"executablePath":{"type":"string","description":"Executable path captured before quit"},"window":{"type":"object","description":"First top-level window of the relaunched process, if found"}},"required":["ok","traceId"]}""";

  private const string AppListInputSchemaJson = """{"type":"object","properties":{"limit":{"type":"integer","default":100,"description":"Maximum number of distinct apps to return"}},"required":[]}""";
  private const string AppListOutputSchemaJson = """{"type":"object","properties":{"ok":{"type":"boolean"},"traceId":{"type":"string"},"apps":{"type":"array","items":{"type":"object","properties":{"processId":{"type":"integer"},"processName":{"type":"string"},"title":{"type":"string"},"active":{"type":"boolean"}},"required":["processId","processName"]}}},"required":["ok","traceId","apps"]}""";
}

